services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=root
      - DB_USER=root
      - DB_PASS=password*1
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password*1
    volumes:
      - ./src/Domain/Migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
